# Generated by Django 4.0.4 on 2022-04-27 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winperday',
            name='day',
            field=models.DateField(verbose_name=datetime.datetime(2022, 4, 27, 16, 38, 41, 482669)),
        ),
    ]
